### ISSUE TITLE
Le field "Lieu" > texte simple

### ISSUE THREAD

**Issue by sographik** [jabberwooki/refuges#12]
Le champ "Lieu" du type de contenu événement doit être un champ de texte simple

**Comment by jabberwooki** [comment]
Il n'est pas possible de changer le widget d'un champ (texte riche -> texte simple) créé dans un type de contenu. Donc j'ai supprimé le champ Lieu existant et j'ai créé un nouveau champ Lieux sous forme de champ texte simple. Je lui ai donné le même nom machine que précédement (field_location) pour éviter de perturber le code css.

**Comment by jabberwooki** [comment]
Kamino cloned this issue to [jabberwooki/refuges2](https://github.com/jabberwooki/refuges2/issues/12)
