### ISSUE TITLE
Améliorer le fonctionnement JS du menu Hamburger

### ISSUE THREAD

**Issue by sographik** [jabberwooki/refuges#4]
Comportement du menu et des sous-menu, voir le positionnement...

**Comment by jabberwooki** [comment]
J'ai mis en place le fonctionnement sliding-menu.
Pour le positionnement, j'ai ouvert un autre ticket : #39

**Comment by jabberwooki** [comment]
Kamino cloned this issue to [jabberwooki/refuges2](https://github.com/jabberwooki/refuges2/issues/4)
