### ISSUE TITLE
Modifier rôle webmaster

### ISSUE THREAD

**Issue by sographik** [jabberwooki/refuges#6]
Accès au menu "Services"
Type de ocntenu "Article" non visible
Le webmaster doit avoir la possibilité de choisir l'ordre des items de menu du menu hamburger

**Comment by jabberwooki** [comment]
- Le rôle webmaster a accès aux menus Hamburger et Services.
- Les rôles webmaster et redacteur ne voient plus le type de contenu Article.
- Le rôle webmaster peut réordonner les items du menu Hamburger. Mais ATTENTION !
Les items Actualités (poids 10), Agenda (poids 11), Media (poids 12) et Services (poids 13) sont embarqués dans la configuration. S'ils sont réordonnés par le webmaster, ils retrouveront leur position initiale à la prochaine synchronisation de configuration. En revanche, il est possible d'ajouter des liens en leur attribuant un poids de 0 à 9. Ceux-ci ne seront pas affectés.

**Comment by jabberwooki** [comment]
Kamino cloned this issue to [jabberwooki/refuges2](https://github.com/jabberwooki/refuges2/issues/6)
